name: Get Version Numbers

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          echo "GITHUB_TOKEN cleared"
          
      - name: Clear the GITHUB_TOKEN environment variable
        run: |
          unset GITHUB_TOKEN

      - name: Get the latest release tag
        id: get_latest_release
        run: |
          latest_release=$(gh release view --json tagName -q .tagName)
          echo "Latest release tag: $latest_release"
          echo "::set-output name=latest_release::$latest_release"

