name: Dispatch Agent Build test

on:
  push:
    branches: [ "main" ]
  
    workflow_demo:

permissions:
    contents: read
    id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
      
    - name: Github Tag name
      run: |
        echo "Tag name from GitHub_Ref_Name: $GITHUB_RUN-NUMBER"
        echo "Tag Name from Github_Ref_Name: ${{ steps.bump_version.outputs.version }}"


    - name: Determine version type
      id: bump_version
      run: |
          export MAJOR: ${{ steps.branchVersion.outputs.major }}
          export MINOR: ${{ steps.branchVersion.outputs.minor }}
          export PATCH: ${{ steps.branchVersion.outputs.patch }}
          MANIFEST_SAFE_VERSION_STRING: ${{ steps.branchVersion.outputs.manifestSafeVersionString }}
          "echo major: $MAJOR minor: $MINOR patch: $PATCH manifestSafeVersionString: $MANIFEST_SAFE_VERSION_STRING"
