name: Get Latest Release Tag

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest release tag
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "$response" > response.json
          tag_name=$(jq -r '.tag_name' response.json)
          echo "Latest release tag: $tag_name"
      # Add more steps as needed
