name: Dispatch Agent Build test

on:
  push:
    branches: [ "main" ]
  
    workflow_demo:

permissions:
    contents: read
    id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339713188249:role/githubactionsrole
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: us-east-2
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://githubactions-agent-bucket --delete

