name: Dispatch Agent Build test

on:
  push:
    branches: [ "main" ]
  
    workflow_demo:

permissions:
    contents: read
    id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless  you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Create tag artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.ref_name }}
        path: Release
    - name: Github Tag name
      run: |
        echo "Tag name from GitHub_Ref_Name: $GITHUB_REF_NAME"
        echo: "Tag Name from Github_Ref_Name: ${{github.ref_name}}"
