name: Dispatch Agent Build test

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

permissions:
    contents: read
    id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Extract version numbers
      id: extract_version
      run: |

          # Remove the leading 'v' if it exists
          VERSION=${VERSION#v}
          
          # Extract major, minor, and patch versions
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "PATCH=$PATCH" >> $GITHUB_ENV

    - name: Output version numbers
      run: |
          echo "Major version: $MAJOR"
          echo "Minor version: $MINOR"
          echo "Patch version: $PATCH"
