name: Build WiX Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install WiX Toolset
      run: |
        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        $wixInstaller = "$env:USERPROFILE\wix311.exe"
        Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
        Start-Process -FilePath $wixInstaller -ArgumentList "/silent" -Wait
        Remove-Item -Path $wixInstaller
      shell: powershell

    - name: Verify WiX Toolset Installation Directory
      run: |
        Get-ChildItem -Path "C:\Program Files (x86)\WiX Toolset v3.11\bin"
      shell: powershell

    - name: Verify WiX Toolset Installation
      run: |
        & "C:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe" -? 
        & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -? 
        & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -? 
      shell: powershell

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build WiX project
      run: msbuild path\to\your\project.wixproj /p:Configuration=Release
      shell: powershell
