name: Build WiX Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install WiX Toolset
      run: |
        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        $wixInstaller = "$env:USERPROFILE\wix311.exe"
        Write-Output "Downloading WiX installer from $wixUrl to $wixInstaller"
        Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
        Write-Output "Running WiX installer"
        Start-Process -FilePath $wixInstaller -ArgumentList "/silent" -Wait -PassThru | Out-String
        Write-Output "Removing WiX installer"
        Remove-Item -Path $wixInstaller
        Write-Output "WiX installation completed"
      shell: powershell

    - name: Verify WiX Toolset Installation Directory
      run: |
        Write-Output "Listing contents of WiX installation directory"
        Get-ChildItem -Path "C:\Program Files (x86)\WiX Toolset v3.11\bin"
      shell: powershell
      continue-on-error: true

    - name: Search Common Program Files Directories
      run: |
        Write-Output "Searching for WiX Toolset in common directories"
        $commonDirs = @(
          "C:\Program Files (x86)",
          "C:\Program Files",
          "C:\ProgramData",
          "$env:USERPROFILE\AppData\Local\Programs"
        )
        foreach ($dir in $commonDirs) {
          Write-Output "Checking $dir"
          Get-ChildItem -Path $dir -Directory | Where-Object { $_.Name -like "WiX*" } | Select-Object -Property FullName
        }
      shell: powershell
      continue-on-error: true

    - name: Search Entire File System for WiX
      run: |
        Write-Output "Searching entire file system for WiX Toolset"
        Get-ChildItem -Path "C:\" -Recurse -Directory | Where-Object { $_.Name -like "WiX*" } | Select-Object -Property FullName
      shell: powershell
      continue-on-error: true

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build WiX project
      run: msbuild path\to\your\project.wixproj /p:Configuration=Release
      shell: powershell
