name: Dispatch Agent Build test

on:
  push:
    branches: [ "main" ]
  
    workflow_demo:

permissions:
    contents: read
    id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
      
    - name: Github Tag name
      run: |
        echo "Tag name from GitHub_Ref_Name: $GITHUB_RUN-NUMBER"
        echo "Tag Name from Github_Ref_Name: ${{ steps.bump_version.outputs.version }}"


    - name: Determine version type
      id: bump_version
      run: |
          export major=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 1)
          export minor=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 2)
          export patch=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 3)

          if [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'major') }}" ]; then
            echo "::set-output name=version::${major}.0.0"
          elif [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'minor') }}" ]; then
            echo "::set-output name=version::${major}.${minor+1}.0"
          else
            echo "::set-output name=version::${major}.${minor}.${patch+1}"
          fi

